### ISSUE TITLE
UI when not signed in

### ISSUE THREAD

**Issue by Nosajool** [Nosajool/League-Of-Valor#14]
**Pages:**
- `/`
- `/signin`
- `/signup`

**Expected:** Colors should be less bright / more like when you are signed in

**Actual:** :astonished: MY EYES

![main page ui](https://cloud.githubusercontent.com/assets/3674579/3367306/02469454-fb5c-11e3-9bbf-44b877f86a68.PNG)

**Comment by AcroMace** [comment]
Fixed https://github.com/Nosajool/League-Of-Valor/commit/ceeb7e275bd00bb4ca3ca4d56db4b4128790652e
