### ISSUE TITLE
Add Battle

### ISSUE THREAD

**Issue by AcroMace** [Nosajool/League-Of-Valor#25]
**Expected**
- Should be able to actually play the game

**Actual**
- Can't :cry:

Please fix @Nosajool :neckbeard:

**Comment by Nosajool** [comment]
Note to self: Create Battle and BattleLog models
Battle will have id, user A id, user B id, user_champ1 id, user_champ2_id, user_champ3_id, user_champ4_id, user_champ5_id, opp_champ1_id etc...

Battle Logs will have id, battle_id, event_description
